server:
  port: 8000
#  Here My api will run on 8082 port

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  # This for my Naming Server URL

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: student-service
          uri: lb://student-service
          predicates:
            - Path=/api/students/**

        - id: different-service
          uri: lb://different-service
          predicates:
            - Path=/api/different/**


#  int-jne-056:student-service:8081